include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # Style rules
    - camel_case_types
    - library_names
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_print
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    - avoid_unnecessary_containers
    # formatting
    - curly_braces_in_flow_control_structures
    # doc comments
    - slash_for_doc_comments
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - empty_statements
    - always_put_control_body_on_new_line
    - empty_constructor_bodies
    - missing_whitespace_between_adjacent_strings
    - depend_on_referenced_packages
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_null_checks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_late
    - unnecessary_getters_setters
    - unnecessary_final
    - sized_box_shrink_expand
    - prefer_is_not_empty
    - prefer_is_empty
    - prefer_contains
    - prefer_adjacent_string_concatenation